/**
 * organization-registration.spec.ts
 *
 * Tests the full 3-tab Organization Registration form:
 *   Tab 1 – Organization Information
 *   Tab 2 – Contact Information
 *   Tab 3 – Supporting Documents
 *
 * All tests use the guestPage fixture (no pre-authenticated session).
 * Test data is generated by OrgRegistrationFactory.
 */

import { test, expect } from '@fixtures/AuthFixtures';
import { Logger } from '@utils/logger';
import { Assertions } from '@utils/assertions';
import { OrganizationRegistrationPage } from '@pages/auth/organization/OrganizationRegistrationPage';
import { OrgRegistrationFactory } from '@utils/factories/OrgRegistrationFactory';
import { NavigationHelper } from '@utils/helpers/navigationHelper';

/* ================================================================
 * SUITE
 * ================================================================ */

test.describe('Organization Registration @auth @registration @organization', () => {

  /* ---------------------------------------------------------------
   * HAPPY PATH – Tab 1 only (smoke guard)
   * --------------------------------------------------------------- */

  test(
    'TC-REG-ORG-001: Navigate to Org Registration page and verify Tab 1 elements @smoke @regression',
    async ({ guestPage,publicPage }) => {
      Logger.testStart('TC-REG-ORG-001');

      // Navigate to Organization Login option
    await test.step('Verify and Navigate to Organization Login', async () => {
       await Assertions.verifyElementVisible(publicPage.organizationRadio, 'ORGANIZATION radio button');
       await publicPage.navigateToOrganizationLogin();
    });

      // Clickon Organization Register button
    await test.step('Navigate to Organization registration page',async() => {
       await Assertions.verifyElementVisible(publicPage.registerButton, 'Organization register button');
       await publicPage.navigateToOrganizationRegistration();
    });

      const regPage = new OrganizationRegistrationPage(guestPage);

      await test.step('Verify Organization Information tab is visible', async () => {
        await Assertions.verifyElementVisible(regPage.tabOrgInfo,'Organization information tab',6000)
        //await regPage.verifyOrgInfoTabVisible();
      });

    await test.step('Verify required fields are present', async () => {
  await Assertions.verifyElementVisible(regPage.radioNonProfitYes, 'Non-Profit Yes radio');
  await Assertions.verifyElementVisible(regPage.radioNonProfitNo, 'Non-Profit No radio');
  await Assertions.verifyElementVisible(regPage.inputLegalName, 'Legal Name field');
  await Assertions.verifyElementVisible(regPage.textareaMission, 'Mission textarea');
  await Assertions.verifyElementVisible(regPage.inputMdCharityId, 'MD Charity ID field');
  await Assertions.verifyElementVisible(regPage.inputFederalTaxId, 'Federal Tax ID field');
  await Assertions.verifyElementVisible(regPage.inputMarylandStateId, 'Maryland State ID field');

  // ✅ FIXED
  await Assertions.verifyElementVisible(regPage.textareaPhysicalAddressLine1, 'Physical Address Line 1');

  await Assertions.verifyElementVisible(regPage.inputPrimaryFirstName, 'Primary Contact First Name');
  await Assertions.verifyElementVisible(regPage.inputPrimaryEmail, 'Primary Contact Email');
  await Assertions.verifyElementVisible(regPage.inputUsername, 'Username field');
  await Assertions.verifyElementVisible(regPage.inputPassword, 'Password field');
  await Assertions.verifyElementVisible(regPage.btnNextTab1, 'Next button');
  await Assertions.verifyElementVisible(regPage.btnResetTab1, 'Reset Form button');
  await Assertions.verifyElementVisible(regPage.btnCancelTab1, 'Cancel button');
});

      Logger.testEnd('TC-REG-ORG-001');
    }
  );

  /* ---------------------------------------------------------------
   * HAPPY PATH – Complete Tab 1 → Tab 2 flow
   * --------------------------------------------------------------- */

  test(
    'TC-REG-ORG-002: Fill Tab 1 and navigate to Tab 2 (Contact Information) @smoke @regression',
    async ({ guestPage }) => {
      Logger.testStart('TC-REG-ORG-002');

      const nav     = new NavigationHelper(guestPage);
      const regPage = new OrganizationRegistrationPage(guestPage);
      const data    = OrgRegistrationFactory.generateTab1Data();

      await test.step('Navigate to Organization Registration page', async () => {
        await nav.goToOrgRegistration();
      });

      await test.step('Fill Organization Information', async () => {
        await regPage.fillOrgInfo(data.orgInfo);
        Logger.success('Organization Information filled');
      });

      await test.step('Fill Primary Contact Details', async () => {
        await regPage.fillPrimaryContact(data.primaryContact);
        Logger.success('Primary Contact Details filled');
      });

      await test.step('Fill User Details', async () => {
        await regPage.fillUserDetails(data.userDetails);
        Logger.success('User Details filled');
      });

      await test.step('Click Next to proceed to Tab 2', async () => {
        await regPage.clickNextOnTab1();
      });

      await test.step('Verify Tab 2 – Contact Information is displayed', async () => {
        await regPage.verifyContactInfoTabVisible();
        await Assertions.verifyElementVisible(regPage.linkAddNewContact, 'Add New Contact button');
        Logger.success('Tab 2 – Contact Information displayed correctly');
      });

      Logger.testEnd('TC-REG-ORG-002');
    }
  );

  /* ---------------------------------------------------------------
   * HAPPY PATH – Add contact on Tab 2 via modal
   * --------------------------------------------------------------- */

  test(
    'TC-REG-ORG-003: Add a contact on Tab 2 via Add Contact modal @regression',
    async ({ guestPage }) => {
      Logger.testStart('TC-REG-ORG-003');

      const nav     = new NavigationHelper(guestPage);
      const regPage = new OrganizationRegistrationPage(guestPage);
      const tab1Data   = OrgRegistrationFactory.generateTab1Data();
      const contactData = OrgRegistrationFactory.generateContact();

      await test.step('Navigate and fill Tab 1', async () => {
        await nav.goToOrgRegistration();
        await regPage.fillOrgInfo(tab1Data.orgInfo);
        await regPage.fillPrimaryContact(tab1Data.primaryContact);
        await regPage.fillUserDetails(tab1Data.userDetails);
        await regPage.clickNextOnTab1();
      });

      await test.step('Click "+ Add New Contact" button', async () => {
        await regPage.clickAddNewContact();
      });

      await test.step('Verify modal is open', async () => {
        await Assertions.verifyElementVisible(regPage.modalAddContact, 'Add Contact modal');
        await Assertions.verifyElementVisible(regPage.modalInputFirstName,  'Modal First Name field');
        await Assertions.verifyElementVisible(regPage.modalInputLastName,   'Modal Last Name field');
        await Assertions.verifyElementVisible(regPage.modalInputEmail,      'Modal Email field');
        await Assertions.verifyElementVisible(regPage.modalInputOfficePhone,'Modal Office Phone field');
        await Assertions.verifyElementVisible(regPage.modalInputUsername,   'Modal Username field');
        await Assertions.verifyElementVisible(regPage.modalInputPassword,   'Modal Password field');
        await Assertions.verifyElementVisible(regPage.modalBtnSubmit,       'Modal Submit button');
        await Assertions.verifyElementVisible(regPage.modalBtnCancel,       'Modal Cancel button');
        Logger.success('Add Contact modal verified');
      });

      await test.step('Fill and submit contact modal', async () => {
        await regPage.fillAndSubmitContactModal(contactData);
      });

      await test.step('Verify contact appears in the table', async () => {
        const found = await regPage.verifyContactInTable(contactData.email);
        expect(found).toBeTruthy();
        Logger.success(`Contact ${contactData.email} found in table`);
      });

      Logger.testEnd('TC-REG-ORG-003');
    }
  );

  /* ---------------------------------------------------------------
   * HAPPY PATH – Navigate to Tab 3 (Supporting Documents)
   * --------------------------------------------------------------- */

  test(
    'TC-REG-ORG-004: Navigate to Tab 3 and verify Supporting Documents checklist @regression',
    async ({ guestPage }) => {
      Logger.testStart('TC-REG-ORG-004');

      const nav     = new NavigationHelper(guestPage);
      const regPage = new OrganizationRegistrationPage(guestPage);
      const tab1Data = OrgRegistrationFactory.generateTab1Data();

      await test.step('Navigate and complete Tab 1', async () => {
        await nav.goToOrgRegistration();
        await regPage.fillOrgInfo(tab1Data.orgInfo);
        await regPage.fillPrimaryContact(tab1Data.primaryContact);
        await regPage.fillUserDetails(tab1Data.userDetails);
        await regPage.clickNextOnTab1();
      });

      await test.step('Skip contacts and move to Tab 3', async () => {
        await regPage.clickNextOnTab2();
      });

      await test.step('Verify Tab 3 – Supporting Documents is displayed', async () => {
        await regPage.verifySupportingDocsTabVisible();
        Logger.success('Tab 3 – Supporting Documents is visible');
      });

      await test.step('Verify all 18 rows are visible in checklist', async () => {
        // Verify the table has 18 rows (1 per document in the checklist)
        const rows = guestPage.locator('table tbody tr');
        const rowCount = await rows.count();
        Logger.info(`Supporting documents table has ${rowCount} rows`);
        expect(rowCount).toBeGreaterThanOrEqual(18);
        Logger.success('All 18 supporting document rows present');
      });

      await test.step('Verify key document descriptions are present', async () => {
        await Assertions.verifyElementVisible(
          guestPage.locator('td:has-text("Attachment A")').first(),
          'Attachment A row'
        );
        await Assertions.verifyElementVisible(
          guestPage.locator('td:has-text("Attachment B")').first(),
          'Attachment B row'
        );
        await Assertions.verifyElementVisible(
          guestPage.locator('td:has-text("IRS Form W-9")').first(),
          'IRS W-9 row'
        );
        await Assertions.verifyElementVisible(
          guestPage.locator('td:has-text("IRS Tax-Exempt")').first(),
          'IRS Tax-Exempt row'
        );
        Logger.success('Key document rows verified');
      });

      await test.step('Verify Upload buttons are present for all rows', async () => {
        const uploadButtons = guestPage.locator('button:has-text("Upload")');
        const btnCount = await uploadButtons.count();
        Logger.info(`Found ${btnCount} Upload buttons`);
        expect(btnCount).toBeGreaterThanOrEqual(18);
        Logger.success('Upload buttons present for all document rows');
      });

      await test.step('Verify Submit, Back, and Cancel buttons are present', async () => {
        await Assertions.verifyElementVisible(
          guestPage.locator('button:has-text("Submit"):visible').first(),
          'Submit button'
        );
        await Assertions.verifyElementVisible(
          guestPage.locator('button:has-text("Back"):visible').first(),
          'Back button'
        );
        Logger.success('Tab 3 action buttons verified');
      });

      Logger.testEnd('TC-REG-ORG-004');
    }
  );

  /* ---------------------------------------------------------------
   * HAPPY PATH – Full registration end-to-end
   * --------------------------------------------------------------- */

  test(
    'TC-REG-ORG-005: Complete full organization registration (all 3 tabs) @e2e @regression',
    async ({ guestPage }) => {
      Logger.testStart('TC-REG-ORG-005');

      const nav      = new NavigationHelper(guestPage);
      const regPage  = new OrganizationRegistrationPage(guestPage);
      const fullData = OrgRegistrationFactory.generateCompleteRegistration();

      Logger.info(`Registering org: ${fullData.tab1.orgInfo.legalName}`);
      Logger.info(`Primary contact: ${fullData.tab1.primaryContact.email}`);

      await test.step('Navigate to Organization Registration page', async () => {
        await nav.goToOrgRegistration();
      });

      await test.step('Tab 1 – Fill Organization Information', async () => {
        await regPage.fillOrgInfo(fullData.tab1.orgInfo);
        Logger.success('Tab 1 org info filled');
      });

      await test.step('Tab 1 – Fill Primary Contact Details', async () => {
        await regPage.fillPrimaryContact(fullData.tab1.primaryContact);
        Logger.success('Tab 1 primary contact filled');
      });

      await test.step('Tab 1 – Fill User Details', async () => {
        await regPage.fillUserDetails(fullData.tab1.userDetails);
        Logger.success('Tab 1 user details filled');
      });

      await test.step('Tab 1 – Click Next to proceed to Tab 2', async () => {
        await regPage.clickNextOnTab1();
        await regPage.verifyContactInfoTabVisible();
      });

      await test.step('Tab 2 – Add contacts via modal', async () => {
        if (fullData.tab2Contacts.length > 0) {
          await regPage.addContacts(fullData.tab2Contacts);
        } else {
          Logger.info('No additional contacts to add');
        }
      });

      await test.step('Tab 2 – Click Next to proceed to Tab 3', async () => {
        await regPage.clickNextOnTab2();
        await regPage.verifySupportingDocsTabVisible();
      });

      await test.step('Tab 3 – Upload available documents', async () => {
        // In automated testing without real files, we skip actual uploads.
        // To upload real files, use: OrgRegistrationFactory.generateDocsWithFiles({ 1: '/path/to/file.pdf' })
        Logger.info('Skipping file uploads (no test files configured) – verifying checklist only');
        const rows = guestPage.locator('table tbody tr');
        const rowCount = await rows.count();
        expect(rowCount).toBeGreaterThanOrEqual(18);
      });

      await test.step('Tab 3 – Submit registration', async () => {
        await regPage.clickSubmit();
      });

      await test.step('Verify registration success', async () => {
        await regPage.verifyRegistrationSuccess();
      });

      Logger.testEnd('TC-REG-ORG-005');
    }
  );

  /* ---------------------------------------------------------------
   * NEGATIVE – Submit Tab 1 with missing required fields
   * --------------------------------------------------------------- */

  test(
    'NEG-TC-REG-ORG-006: Submit Tab 1 without filling required fields @negative @regression',
    async ({ guestPage }) => {
      Logger.testStart('NEG-TC-REG-ORG-006');

      const nav     = new NavigationHelper(guestPage);
      const regPage = new OrganizationRegistrationPage(guestPage);

      await test.step('Navigate to Organization Registration page', async () => {
        await nav.goToOrgRegistration();
      });

      await test.step('Click Next without filling any fields', async () => {
        await regPage.clickNextOnTab1();
      });

      await test.step('Verify we stay on Tab 1 (validation prevented navigation)', async () => {
        // Either browser validation messages appear, or server-side errors display
        await guestPage.waitForTimeout(1000);
        const currentUrl = guestPage.url();
        Logger.info(`Current URL after submit attempt: ${currentUrl}`);

        // Verify the Legal Name field triggers HTML5 required validation
        const legalNameValidation = await regPage.getValidationMessage(regPage.inputLegalName);
        Logger.info(`Legal Name validation message: "${legalNameValidation}"`);

        // Page should not have moved to contact information tab
        const onContactTab = await regPage.isElementVisible(regPage.btnAddNewContact, 2000);
        expect(onContactTab).toBeFalsy();
        Logger.success('Validation prevented form submission without required fields');
      });

      Logger.testEnd('NEG-TC-REG-ORG-006');
    }
  );

  /* ---------------------------------------------------------------
   * NEGATIVE – Modal submit without required fields
   * --------------------------------------------------------------- */

  test(
    'NEG-TC-REG-ORG-007: Submit Add Contact modal without required fields @negative @regression',
    async ({ guestPage }) => {
      Logger.testStart('NEG-TC-REG-ORG-007');

      const nav     = new NavigationHelper(guestPage);
      const regPage = new OrganizationRegistrationPage(guestPage);
      const tab1Data = OrgRegistrationFactory.generateTab1Data();

      await test.step('Navigate and complete Tab 1', async () => {
        await nav.goToOrgRegistration();
        await regPage.fillOrgInfo(tab1Data.orgInfo);
        await regPage.fillPrimaryContact(tab1Data.primaryContact);
        await regPage.fillUserDetails(tab1Data.userDetails);
        await regPage.clickNextOnTab1();
      });

      await test.step('Open Add Contact modal', async () => {
        await regPage.clickAddNewContact();
        await Assertions.verifyElementVisible(regPage.modalAddContact, 'Add Contact modal');
      });

      await test.step('Click Submit without filling modal fields', async () => {
        await regPage.clickElement(regPage.modalBtnSubmit, 'Modal Submit button');
        await guestPage.waitForTimeout(1000);
      });

      await test.step('Verify modal still open or validation errors shown', async () => {
        // Modal should remain open if validation fails
        const firstNameValidation = await regPage.getValidationMessage(regPage.modalInputFirstName);
        Logger.info(`First Name validation message: "${firstNameValidation}"`);

        // Modal should still be visible
        const modalStillOpen = await regPage.isElementVisible(regPage.modalAddContact, 3000);
        Logger.info(`Modal still open: ${modalStillOpen}`);
        Logger.success('Validation verified for empty modal submission');
      });

      Logger.testEnd('NEG-TC-REG-ORG-007');
    }
  );

  /* ---------------------------------------------------------------
   * NEGATIVE – Cancel modal discards data
   * --------------------------------------------------------------- */

  test(
    'NEG-TC-REG-ORG-008: Cancel Add Contact modal discards entered data @negative @regression',
    async ({ guestPage }) => {
      Logger.testStart('NEG-TC-REG-ORG-008');

      const nav      = new NavigationHelper(guestPage);
      const regPage  = new OrganizationRegistrationPage(guestPage);
      const tab1Data = OrgRegistrationFactory.generateTab1Data();
      const contactData = OrgRegistrationFactory.generateContact();

      await test.step('Navigate and complete Tab 1', async () => {
        await nav.goToOrgRegistration();
        await regPage.fillOrgInfo(tab1Data.orgInfo);
        await regPage.fillPrimaryContact(tab1Data.primaryContact);
        await regPage.fillUserDetails(tab1Data.userDetails);
        await regPage.clickNextOnTab1();
      });

      await test.step('Open modal and fill some data', async () => {
        await regPage.clickAddNewContact();
        await regPage.fillInput(regPage.modalInputFirstName, contactData.firstName, 'First Name');
        await regPage.fillInput(regPage.modalInputEmail, contactData.email, 'Email');
      });

      await test.step('Cancel the modal', async () => {
        await regPage.clickElement(regPage.modalBtnCancel, 'Modal Cancel button');
        await guestPage.waitForTimeout(500);
      });

      await test.step('Verify modal is closed', async () => {
        const modalOpen = await regPage.isElementVisible(regPage.modalAddContact, 2000);
        expect(modalOpen).toBeFalsy();
        Logger.success('Modal closed after Cancel');
      });

      await test.step('Verify contact was NOT added to table', async () => {
        const contactFound = await regPage.verifyContactInTable(contactData.email);
        expect(contactFound).toBeFalsy();
        Logger.success('Cancelled contact was not added to the table');
      });

      Logger.testEnd('NEG-TC-REG-ORG-008');
    }
  );

  /* ---------------------------------------------------------------
   * NEGATIVE – Reset form clears all Tab 1 data
   * --------------------------------------------------------------- */

  test(
    'NEG-TC-REG-ORG-009: Reset Form on Tab 1 clears all entered data @negative @regression',
    async ({ guestPage }) => {
      Logger.testStart('NEG-TC-REG-ORG-009');

      const nav     = new NavigationHelper(guestPage);
      const regPage = new OrganizationRegistrationPage(guestPage);
      const tab1Data = OrgRegistrationFactory.generateTab1Data();

      await test.step('Navigate and fill Tab 1 partially', async () => {
        await nav.goToOrgRegistration();
        await regPage.fillInput(regPage.inputLegalName, tab1Data.orgInfo.legalName, 'Legal Name');
        await regPage.fillInput(regPage.textareaMission, tab1Data.orgInfo.mission, 'Mission');
      });

      await test.step('Verify data is entered', async () => {
        const legalNameValue = await regPage.inputLegalName.inputValue();
        expect(legalNameValue).toBe(tab1Data.orgInfo.legalName);
        Logger.success('Data confirmed before reset');
      });

      await test.step('Click Reset Form', async () => {
        await regPage.clickResetTab1();
      });

      await test.step('Verify fields are cleared', async () => {
        const legalNameAfterReset = await regPage.inputLegalName.inputValue();
        expect(legalNameAfterReset).toBe('');
        Logger.success('Fields cleared after Reset Form');
      });

      Logger.testEnd('NEG-TC-REG-ORG-009');
    }
  );
});